server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://123.57.138.109:3306/agricultural_machinery
    name: root
    data-password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.jstdoit.agriculturalmachinery.entity
  mapper-locations: classpath:mysql/mapper/*.xml
logging:
  level:
    com.jstdoit.agriculturalmachinery.dao: debug